A TRIBUTE TO THE GREAT AMERICAN ARTIST, ROBERT INDIANA.
HIS GREATEST WORK WILL BE REPRODUCED WITH A MESSAGE OF
YOUR CHOICE UP TO 32 CHARACTERS.  IF YOU CAN'T THINK OF
A MESSAGE, SIMPLE TYPE THE WORD 'LOVE'


LOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVE
L            OVELOVELOVELOVELOVELOVELOV         LOVELOVELOVE
LOV        ELOVELOVELOVELOVELOVELOV                 LOVELOVE
LOVE      VELOVELOVELOVELOVELOVEL                     VELOVE
LOVE      VELOVELOVELOVELOVELOVE            LOVEL      ELOVE
LOVE      VELOVELOVELOVELOVELOV           VELOVELO      LOVE
LOVE      VELOVELOVELOVELOVELOV          OVELOVELOV     LOVE
LOVE      VELOVELOVELOVELOVELOV         LOVELOVELOV     LOVE
LOVE      VELOVELOVELOVELOVELOV        ELOVELOVELO      LOVE
LOVE      VELOVELOVELOVELOVELOV       VELOVELOVEL       LOVE
LOVE      VELOVELOVELOVELOVELOV      OVELOVELOVE        LOVE
LOVE      VELOVELOVELOVELOVEL V     LOVELOVELOV         LOVE
LOVE      VELOVELOVELOVELOVEL V     LOVELOVELO          LOVE
LOVE      VELOVELOVELOVELOVE  V      OVELOVEL           LOVE
LOVE      VELOVELOVELOVELOV   V       VELOV             LOVE
LOVE      VELOVELOVELOVEL     VE                       ELOVE
L                             VELOV                 LOVELOVE
L                             VELOVELOV         LOVELOVELOVE
L             VELOV                                        E
L             VELOV                                        E
LOVE      VELOVELOVELOV   VELOVELOVE      VELOVELOVELO     E
LOVEL      ELOVELOVELO   OVELOVELOVE      VELOVELOVELOVE   E
LOVEL      ELOVELOVELO   OVELOVELOVE      VELOVELOVELOVEL  E
LOVELO      LOVELOVEL   LOVELOVELOVE      VELOVELOVELOVELO E
LOVELO      LOVELOVEL   LOVELOVELOVE      VELOVEL VELOVELOVE
LOVELOV      OVELOVE   ELOVELOVELOVE      VELOVE  VELOVELOVE
LOVELOV      OVELOVE   ELOVELOVELOVE              VELOVELOVE
LOVELOVE      VELOV   VELOVELOVELOVE      VELOVE  VELOVELOVE
LOVELOVE      VELOV   VELOVELOVELOVE      VELOVEL VELOVELOVE
LOVELOVEL      ELO   OVELOVELOVELOVE      VELOVELOVELOVELO E
LOVELOVEL      ELO   OVELOVELOVELOVE      VELOVELOVELOVEL  E
LOVELOVELO      L   LOVELOVELOVELOVE      VELOVELOVELOVE   E
LOVELOVELO          LOVELOVELOVELOVE      VELOVELOVELO     E
LOVELOVELOV        ELOVELOVELOVE                           E
LOVELOVELOV        ELOVELOVELOVE                           E
LOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVELOVE
