MIDNIGHT DREARY
PROPHET
     THRILLED ME
SHALL BE LIFTED
     NOTHING MORE 
MIDNIGHT DREARY BURNED QUOTH THE RAVEN
     ...EVERMORE

FIERY EYES BURNED, SIGN OF PARTING, ...EVERMORE

THING OF EVIL
     THRILLED ME
SHALL BE LIFTED NOTHING MORE 
PROPHET,
     BURNED
QUOTH THE RAVEN
     ...EVERMORE 

