MIDNIGHT DREARY FIERY EYES BEGUILING ME AND MY SOUL NEVERMORE 
THING OF EVIL,
     STILL SITTING.... DARKNESS THERE,
     NOTHING MORE 
THING OF EVIL BURNED, DARKNESS THERE NEVERMORE,

PROPHET BURNED
DARKNESS THERE
     NEVERMORE 
BIRD OR FIEND
     STILL SITTING....
DARKNESS THERE ...EVERMORE


