MIDNIGHT DREARY
PROPHET BEGUILING ME
AND MY SOUL
     YET AGAIN 
PROPHET THRILLED ME AND MY SOUL NEVERMORE 
PROPHET, STILL SITTING....
AND MY SOUL
     NOTHING MORE 
FIERY EYES THRILLED ME QUOTH THE RAVEN NEVERMORE 
PROPHET
     NEVER FLITTING
QUOTH THE RAVEN SLOWLY CREEPING 

