I AM THINKING OF A WORD -- YOU GUESS IT.  I WILL GIVE YOU
CLUES TO HELP YOU GET IT.  GOOD LUCK!!

YOU ARE STARTING A NEW GAME...
GUESS A FIVE LETTER WORD? THERE WERE 1 MATCHES AND THE COMMON LETTERS WERE...K
FROM THE EXACT LETTER MATCHES, YOU KNOW................---K-

IF YOU GIVE UP, TYPE '?' FOR YOUR NEXT GUESS.

GUESS A FIVE LETTER WORD? THERE WERE 5 MATCHES AND THE COMMON LETTERS WERE...DINKY
FROM THE EXACT LETTER MATCHES, YOU KNOW................DINKY
YOU HAVE GUESSED THE WORD.  IT TOOK 2 GUESSES!

WANT TO PLAY AGAIN? 