10 REM "BUZZWORD GENERATOR from 101 BASIC Games"
20 REM "Ported to Stefan's BASIC in 2021"
100 PRINT "THIS PROGRAM PRINTS HIGHLY ACCEPTABLE PHRASES IN"
110 PRINT "'EDUCATOR-SPEAK'THAT YOU CAN WORK INTO REPORTS"
120 PRINT "AND SPEECHES.  WHENEVER A QUESTION MARK IS PRINTED,"
130 PRINT "TYPE A 'Y' FOR ANOTHER PHRASE OR 'N' TO QUIT."
140 PRINT "HERE'S THE FIRST PHRASE:"
150 @R=MILLIS(1)
300 FOR P
305 PRINT "** ";
310 FOR I=1 TO 3
320 A=INT(RND(13))+1
330 FOR J=1 TO A: READ A$: NEXT
340 PRINT A$;" ";
350 FOR J=A+1 TO 13: READ A$: NEXT
360 NEXT I
370 RESTORE
375 PRINT
380 INPUT "ANOTHER PHRASE? ";Y$ 
390 IF Y$<>"Y" AND Y$<>"y" THEN BREAK
400 NEXT
500 PRINT "COME BACK WHEN YOU NEED HELP WITH ANOTHER REPORT!"
510 END
600 DATA "ABILITY","BASAL","BEHAVIORAL","CHILD-CENTERED"
610 DATA "DIFFERENTIATED","DISCOVERY","FLEXIBLE","HETEROGENEOUS"
620 DATA "HOMOGENEOUS","MANIPULATIVE","MODULAR","TAVISTOCK"
630 DATA "INDIVIDUALIZED","LEARNING","EVALUATIVE","OBJECTIVE"
640 DATA "COGNITIVE","ENRICHMENT","SCHEDULING","HUMANISTIC"
650 DATA "INTEGRATED","NON-GRADED","TRAINING","VERTICAL AGE"
660 DATA "MOTIVATIONAL","CREATIVE","GROUPING","MODIFICATION"
670 DATA "ACCOUNTABILITY","PROCESS","CORE CURRICULUM","ALGORITHM"
680 DATA "PERFORMANCE","REINFORCEMENT","OPEN CLASSROOM","RESOURCE"
690 DATA "STRUCTURE","FACILITY","ENVIRONMENT"

